//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int id { get; set; }
        public int userId { get; set; }
        public double amount { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string paidDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
